config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'articles#index'

  mount API::Root => '/'
  mount GrapeSwaggerRails::Engine => '/docs'

  devise_for :users, :controllers => { :omniauth_callbacks => 'users/omniauth_callbacks' }

  devise_scope :user do
    get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  resources :articles do
    collection do
      match 'search' => 'articles#search', via: [:get, :post], as: :search
    end

    get 'history'
    get 'lock'
    get 'unlock'
  end

  resources :templates do
    get 'lock'
    get 'unlock'
  end

  resources :stars, only: [:create, :destroy]
  resources :comments, only: [:create, :update, :destroy]
  resources :uploader, only: [:index, :form, :upload, :download]
  resources :users, only: [:index]
  resources :users, path: '/', only: [:edit, :show, :update]
end

app/models/article.rb
# == Schema Information
#
# Table name: articles
#
#  id         :integer          not null, primary key
#  title      :string           not null
#  text       :text             not null
#  user_id    :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  status     :string
#  lock       :boolean          default(FALSE)
#  notice     :boolean          default(TRUE)
#
# Indexes
#
#  index_articles_on_title    (title)
#  index_articles_on_user_id  (user_id)
#

class Article < ActiveRecord::Base
  extend Enumerize
  enumerize :status, in: [:publish, :limit, :wip], default: :limit

  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :histories
  has_many :stars

  validates :title, presence: true
  validates :text, presence: true
  validates :user, presence: true

  scope :sorted_by_recently, -> { reorder('updated_at DESC') }
  scope :recently_edit, -> { reorder('updated_at DESC').take(5) }
  scope :recently_create, -> { reorder('created_at DESC').take(5) }
  scope :with_associations, -> { includes(:tags, :user) }

  acts_as_taggable

  paginates_per 20

  # NOTE: n+1対応, tags に含まれる情報なのに tag_list で 再び query が走る
  def tag_names
    tags.map &:name
  end

  def written_by?(user)
    user == self.user
  end

  def unlock?
    !self.lock
  end

  def to_date_str
    # TODO: use module
    return diff(updated_at, Time.current)
  end

  def diff(src, dist)
    d = dist - src

    if d >= 1.month
      (d / 1.month).round.to_s + 'mo'
    elsif d >= 1.day
      (d / 1.day).round.to_s + 'd'
    elsif d >= 1.hour
      (d / 1.hour).round.to_s + 'h'
    elsif d >= 1.minute
      (d / 1.minute).round.to_s + 'm'
    else
      (d / 1.seconds).round.to_s + 's'
    end
  end

  # 最新の更新は新規投稿のみである？
  def only_created?
    # histories.size == 1
    updated_at == created_at
  end

  # TODO: template STL
  def set_compare(compare)
    @compare = compare
  end

  def star_count_list
    stars      = self.stars.includes(:user)
    count_list = Hash.new(0)
    stars.map do |star|
      count_list[star.user] += 1
    end
    count_list.map { |user, c| { user: user, count: c } }
  end

  def add_star(user)
    stars.create(user_id: user.id)
  end
end

app/controllers/articles_controller.rb
# noinspection ALL
class ArticlesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :published?, only: [:show]
  before_action :check_article_owner, only: [:destroy]
  before_action :locked?, only: [:edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    if params[:tag]
      @articles = @q.result.with_associations.tagged_with(params[:tag]).sorted_by_recently.page(params[:page])
    else
      @articles = @q.result.with_associations.sorted_by_recently.page(params[:page])
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @comments = @article.comments.order('created_at').includes(:user)

    user_ids           = History.where(article: @article).pluck(:user_id)
    @user              = @article.user
    @editors           = User.find(user_ids).uniq
    @stars             = @article.stars.includes(:user)
    @recently_articles = @user.articles.includes(:tags).recently_edit
    @recently_histories         = @article.histories.includes(:user).order('created_at desc').take(5)
    if @user.screen_name == 'esa'
      flash.now[:notice] = t '.esa_message'
    end
  end

  # GET /articles/history/1
  def history
    @article   = Article.find(params[:article_id])
    @histories = @article.histories.includes(:user).order('created_at desc')
    @css = Diffy::CSS
  end

  # GET /articles/new
  def new
    @article   = Article.new
    @templates = Template.includes(:tags)
    compare    = Compare.new(current_user)
    @templates.map { |template| template.set_compare(compare) }
    @tag_list = ActsAsTaggableOn::Tag.all.map &:name
  end

  # GET /articles/1/edit
  def edit
    @tag_list = ActsAsTaggableOn::Tag.all.map &:name
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = current_user.articles.create(article_params)

    respond_to do |format|
      if @article.save
        History.create(user: current_user, article: @article, diff: diff = Diffy::Diff.new('', @article.text))

        if @article.notice
          SlackHook.new.post(current_user, t('.slack_message', {
              user:  @article.user.screen_name,
              title: @article.title,
              url:   full_path(article_path(@article))
          }), @article.text)
        end

        format.html { redirect_to @article, flash: { success: '記事を作成しました' } }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      # diff = Diffy::Diff.new(article_params[:text], @article.text, :context => 1)
      diff = Diffy::Diff.new(@article.text, article_params[:text], :context => 2)
      if article_params[:title] != @article.title
        title_diff =  t('diff.title', { pre_title: @article.title, title: article_params[:title] })
      end
      if @article.update(article_params)
        slack_text = ''
        if diff.to_s != ''
          slack_text = diff.to_s
          History.create(user: current_user, article: @article, diff: diff.to_s(:html))
        end
        if title_diff
          slack_text = title_diff
          History.create(user: current_user, article: @article, diff: title_diff)
        end
        if @article.notice and slack_text != ''
          SlackHook.new.post(current_user, t('.slack_message', {
              user:  @article.user.screen_name,
              title: @article.title,
              url:   full_path(article_path(@article))
          }), slack_text)
          p slack_text
        end

        format.html { redirect_to @article, flash: { success: '記事を更新しました' } }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, flash: { success: '記事を削除しました' } }
      format.json { head :no_content }
    end
  end

  def search
    index
    render :index
  end

  def lock
    @article = Article.find(params[:article_id])
    return if @article.lock?
    @article.lock = true
    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, flash: { success: '記事を保護しました' } }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def unlock
    @article = Article.find(params[:article_id])
    return if @article.unlock?
    @article.lock = false
    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, flash: { success: '保護を解除しました' } }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def published?
    unless @article.status.publish?
      authenticate_user!
    end
  end

  def locked?
    if !@article.written_by?(current_user) && @article.lock
      redirect_to @article
    end
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_article
    @article = Article.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def article_params
    params.require(:article).permit(:title, :text, :status, :tag_list, :user_id, :lock, :notice)
  end

  def check_article_owner
    unless current_user.owner?(@article)
      # TODO: セキュリティ上メッセージは消す
      redirect_to @article, notice: '記事の作者ではありません'
    end
  end

end

app/helpers/articles_helper.rb
module ArticlesHelper
  include ActsAsTaggableOn::TagsHelper
end

app/views/articles/_article.html.slim
li.article-item-box
  .article-icon
    = image_tag article.user.image.url, class: 'img-circle', size: '64x64'
  .info
    .info-head
      .created
        = render partial: 'articles/author_info', locals: { article: article }
        - if article.status.publish?
          = fa_icon 'rocket'
        - unless article.unlock?
          = fa_icon 'lock'
    .info-title
      h2.title
        - if article.status.wip?
          == link_to "[WIP] #{article.title}", article, class: 'wip'
        - else
          = link_to article.title, article
      = link_tags_list_for(article.tags)
      .star
        - article.stars.includes(:user).group(:user_id).each do |star|
          = render partial: 'stars/article_star', locals: { star: star }

app/views/articles/_article_with_star.html.slim
li.article-item-box
  .article-icon
    = image_tag article.user.image.url, class: 'img-circle', size: '64x64'
  .info
    .info-head
      .created
        span.author
          = link_to article.user.screen_name, user_path(article.user)
        |  が 
        span.date
          = l(article.updated_at)
        |  に 
        span
          - if article.only_created?
            |  投稿 
          - else
            |  編集 
        - if article.status.publish?
          = fa_icon 'rocket'
        - unless article.unlock?
          = fa_icon 'lock'
    .info-title
      h2.title
        = link_to article.title, article
      = link_tags_list_for(article.tags)
      .star
        - star_user.each do |star|
          = render partial: 'stars/article_star', locals: { star: star }

app/views/articles/_author_info.html.slim
- if article.only_created?
    - w = '投稿'
- else
    - w = '編集'

span.author
  = link_to article.user.screen_name, user_path(article.user)
span.date
  = "が#{l(article.updated_at)}に#{w}"

app/views/articles/_form.html.slim
= simple_form_for(@article) do |f|
  - if defined? @templates
    .dropdown.pull-right
      button.btn.btn-default.dropdown-toggle[type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true"]
        | Template
        span.caret
      ul#templates-dropdown-list.dropdown-menu
        - @templates.each do |template|
          li.template-item[data-name=template.name data-title=template.title_vr data-text=template.text_vr data-tags=template.tags_vr.join(',')]
            a.emojable[href='#']
              = template.name
        li.divider
        li
          = link_to new_template_path do
            = fa_icon :plus
            | テンプレート追加
        li
          = link_to templates_path do
            = fa_icon :list
            | テンプレート管理
  .field
    = f.input :title, class: 'form-control', input_html: { placeholder: 'タイトル' }
  .field
    = f.input :tag_list, class: 'form-control', input_html: {value: @article.tags.join(','), placeholder: ',区切りでタグを入力' }
  .field
    = f.input :text, class: 'form-control'
  hr
  .row
    .col-sm-2
      a#upload-btn.btn.btn-default
        = fa_icon 'file-image-o'
      input#async-image-data.hide[type="file" name="article[image]"]
    .col-sm-2
      = f.input :notice, label: 'Slackへ通知'
    .col-sm-4
      = f.input :status, label: false
    .col-sm-4
      = f.submit id: 'btn-submit', class: 'form-control'

javascript:
  $(function() {
    var tags = #{raw @tag_list};
    $('#article_tag_list').textcomplete([{
      match: /(^|,)([^\s]*)$/,
      search: function (term, callback) {
        callback($.map(tags, function (tag) {
          if (tag.indexOf(term) == 0) {
            return tag;
          }
          return null;
        }));
      },
      replace: function (value) {
        return "$1" + value;
      },

      index: 2,
      maxCount: 10,
      template: function (value) {
        return value;
      }
    }]);
  });

coffee:
  # タイトルプレビュー反映
  update_title_preview = ->
    $("#title-preview").html(marked($("#article_title").val()))

  # 本文プレビュー反映
  update_text_preview = ->
    marked_text = marked($("#article_text").val())
    $("#text-preview-area").html(marked_text)
    emojify.run($("#text-preview-area").get(0))

  update_tags_preview = ->
    $('#tags-preview').empty()
    tags = $('#article_tag_list').val().split(',')
    $.each tags, (i, v) ->
      return if v == ''
      $('#tags-preview').append($('<li/>').append($('<span/>').text(v)))

  # 全プレビュー反映
  update_preview = ->
    update_title_preview()
    update_text_preview()
    update_tags_preview()

  # 画像マークダウンの挿入
  insertImgMd = (url) ->
    target = $('#article_text')
    img_md = "![#{url}](#{url})\n"
    insertAtCaret(target, img_md)
    update_text_preview()

  # ターゲット要素のカーソル位置にテキストを挿入
  insertAtCaret = (target, str) ->
    target.focus()
    if navigator.userAgent.match(/MSIE/)
      r = document.selection.createRange()
      r.text = str
      r.select()
    else
      s = target.val()
      p = target.get(0).selectionStart
      np = p + str.length
      target.val(s.substr(0, p) + str + s.substr(p))
      target.get(0).setSelectionRange(np, np)

  $ ->
    # ページ読み込み時にプレビュー反映
    update_preview()

    # 変更イベント
    $("#article_title").keyup update_title_preview
    $("#article_text").keyup update_text_preview
    $("#article_tag_list").keyup update_tags_preview

    $('#upload-btn').click ->
      $('#async-image-data')[0].click()
      return false

    # 画像アップロードボタン
    $('#async-image-data').change ->
      if $(@).files < 1
        return
      file = $(this)[0].files[0]
      if file.clientHeight > 2000 or file.clientWidth > 2000
        alert '画像アップロードでエラーが発生しました 画像サイズが大きいです'
        return

      fd = new FormData()
      fd.append('name', 'jquery test')
      fd.append('file', file)

      $.ajax
        url: '/api/v1/images/upload'
        method: "POST"
        data: fd
        processData: false
        contentType: false
        success: (json) ->
          url = json.file.url
          insertImgMd('http://' + window.location.host + url)
        error: (json) ->
          alert '画像アップロードでエラーが発生しました'
      $('#async-image-data').val('')

  # テンプレートのクリック
  $('#templates-dropdown-list li').click ->
    $('#article_title').val($(this).data('title'))
    $('#article_text').val($(this).data('text'))
    $('#article_tag_list').val($(this).data('tags'))
    update_preview()

app/views/articles/_icons.html.slim
- if @article.written_by?(current_user) || @article.unlock?
  = link_to edit_article_path(@article) do
    = fa_icon 'pencil'
- if @article.lock?
  = fa_icon 'lock'
- if @article.status.publish?
  = fa_icon 'rocket'

app/views/articles/_lock.html.slim
- if user_signed_in? && current_user.owner?(@article)
  - if @article.unlock?
    = link_to article_lock_path(@article) do
      = fa_icon :lock
      | 記事を保護する
  - elsif @article.lock?
    = link_to article_unlock_path(@article) do
      =  fa_icon :lock
      | 記事の保護を解除する

app/views/articles/_tag_list.html.slim
.tag_list_block
  = link_tags_list_for(article.tags, true)
  .add_tag_form.hide
    .input-group.input-group-sm
      span#tag_addon.input-group-addon = '#'
      input#add_tag_text.form-control[type="text" placeholder="タグ" aria-describedby="tag_addon"]
      a#add_tag_btn.input-group-addon[href='#'] = '+ 登録'
  a#edit_tag[href='#' article-id=article.id]
    = fa_icon 'wrench'
    | 編集

coffee:
  $ ->
    del_clicked = ->
      data =
        article_id: $('#edit_tag').attr('article-id')
        tag: $(this).attr('tag_text')
      $.ajax
        url: '/api/v1/tags'
        type: 'DELETE'
        data: data
        success: (json) =>
          $(this).parent().remove()

    # タグ編集モードトグル
    $('#edit_tag').click ->
      if not $(this).hasClass('on')
        $(this).addClass('on')
        $(this).text('タグ編集完了')
        $('.add_tag_form').removeClass('hide');
        $('.delete-tag').removeClass('hide')
      else
        $(this).removeClass('on')
        $(this).text('タグ編集')
        $('.add_tag_form').addClass('hide');
        $('.delete-tag').addClass('hide')

    $('#add_tag_btn').click ->
      tag = $('#add_tag_text').val()
      if tag == "" or $('.tag_list_block').find("li[tag_name=#{tag}]").length > 0
        return

      $('#add_tag_text').val('')
      data =
        article_id: $('#edit_tag').attr('article-id')
        tag: tag
      $.post '/api/v1/tags',
        data,
        (json) =>
          $li = $('<li />').attr('tag_name', tag)
          $li.append $('<a />').attr('href', '/articles?tag=' + tag).html(tag)
          $li.append $('<a />').attr('href', '#').attr('tag_text', tag).addClass('delete-tag').html('x').click del_clicked
          $('.tag_list_block>.tag_list').append($li)

    # タグ削除ボタン
    $('.delete-tag').click del_clicked

app/views/articles/edit.html.slim
- provide(:title, @article.title)
.container-fluid
  h1.page-title
    | 記事編集
  .row
    .col-lg-6
      = render 'form', template_on: false
    |  <meta id="current-user-info" screen_name="
    = current_user.screen_name
    | " name="
    = current_user.name
    | ">
    .col-lg-6
      ul#tags-preview.tag_list
      h2#title-preview
      hr
      #text-preview-area.markdown-body

app/views/articles/history.html.slim
- provide(:title, @article.title)

.container
  h1.page-title
    |  記事編集履歴
  h1
    = @article.title

  .container
  = render @histories

style
  == @css

app/views/articles/index.html.slim
.container
  h1.page-title
    |  記事一覧
    - if params[:tag]
      = fa_icon 'tag'
      = params[:tag]
  ul.articles
    = render @articles
  = paginate @articles

app/views/articles/new.html.slim
- provide(:title, @article.title)
.container-fluid
  h1.page-title
    | 記事作成
  .row
    .col-lg-6
      = render 'form'
    |  <meta id="current-user-info" screen_name="
    = current_user.screen_name
    | " name="
    = current_user.name
    | " >
    .col-lg-6
      ul#tags-preview.tag_list
      h2#title-preview
      hr
      #text-preview-area.markdown-body

app/views/articles/show.html.slim
- provide(:title, @article.title)
.article-header
  .container
    .article-titles
      h1.title
        = @article.title
        = render partial: 'icons', locals: { article: @article }
      = render partial: 'articles/author_info', locals: { article: @article }
      = render partial: 'articles/lock', locals: { article: @article }
      = link_to @article, method: :delete, data: { confirm: '本当に削除しますか？' } do
        = fa_icon :trash
        | 削除
    .article-subinfos
      - @editors.each do |editor|
        = link_to(editor) do
          = image_tag editor.image.url, class: 'img-circle', size: '32x32'
.tag-header
  .container
    = render partial: 'articles/tag_list', locals: { article: @article }

.container
  .article-body.row
    .col-md-8
      .article-text
        #text-preview.markdown-body
      hr
      .star
        - if user_signed_in?
          = link_to stars_path(star: { article_id: @article, user_id: current_user.id }), class: 'star__button', method: :post, remote: true do
            = fa_icon 'thumbs-o-up'
        #star__list
          = render @stars
      hr
      #comment
        = render @comments
      - if user_signed_in?
        = render 'comments/form'
    .col-md-4
      = image_tag @user.image.url, class: 'img-circle', size: '64x64'
      = link_to @user.screen_name, @user
      .article__show
        h4 新着の投稿
        = render partial: 'article', collection: @recently_articles
      .article-subinfos.article-history
        h4 編集履歴
        - @recently_histories.each do |history|
          = render 'histories/simple_history', history: history
          hr
        .more
          .more-history
            = link_to 'もっと見る', article_path(@article) + '/history'

javascript:
  $(function () {
    $('#text-preview').html(marked(#{raw @article.text.to_json}));
    emojify.run($("#text-preview").get(0));
    $('pre code').each(function (i, block) {
      hljs.highlightBlock(block);
    })
  });