config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'articles#index'

  mount API::Root => '/'
  mount GrapeSwaggerRails::Engine => '/docs'

  devise_for :users, :controllers => { :omniauth_callbacks => 'users/omniauth_callbacks' }

  devise_scope :user do
    get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  resources :articles do
    collection do
      match 'search' => 'articles#search', via: [:get, :post], as: :search
    end

    get 'history'
    get 'lock'
    get 'unlock'
  end

  resources :templates do
    get 'lock'
    get 'unlock'
  end

  resources :stars, only: [:create, :destroy]
  resources :comments, only: [:create, :update, :destroy]
  resources :uploader, only: [:index, :form, :upload, :download]
  resources :users, only: [:index]
  resources :users, path: '/', only: [:edit, :show, :update]
end

app/views/templates/_form.html.slim
= simple_form_for(@template) do |f|
  .field
    = f.input :name, label: 'テンプレート名', input_html: { class: 'form-control' }
  .field
    = f.input :title, label: 'タイトル', input_html: { class: 'form-control', placeholder: 'タイトル' }
  .field
    = f.input :tag_list, input_html: { value: @template.tag_list.join(','), class: 'form-control', placeholder: ',区切りでタグを入力' }
  .field
    = f.input :text, class: 'form-control', html: { class: 'comp-text' }
  .field
    = f.input :type, as: :hidden, input_html: { value: 'Template' }
  hr
  .row
    .col-sm-4
      a#upload-btn.btn.btn-default
        = fa_icon 'file-image-o'
      input#async-image-data.hide[type="file" name="template[image]"]
    .col-sm-4
      = f.button :submit, id: 'btn-submit', class: 'form-control'

javascript:
  $(function() {
    var tags = #{raw @tag_list};
    $('#template_tag_list').textcomplete([{
      match: /(^|,)(\w*)$/,
      search: function (term, callback) {
        callback($.map(tags, function (tag) {
          if (tag.indexOf(term) == 0) {
            return tag;
          }
          return null;
        }));
      },
      replace: function (value) {
        return "$1" + value;
      },

      index: 2,
      maxCount: 10,
      template: function (value) {
        return value;
      }
    }]);
  });

coffee:
  # タイトルプレビュー反映
  update_title_preview = ->
    $("#title-preview").html(marked($("#template_title").val()))

  # 本文プレビュー反映
  update_text_preview = ->
    marked_text = marked($("#template_text").val())
    $("#text-preview-area").html(marked_text)
    emojify.run($("#text-preview-area").get(0))

  update_tags_preview = ->
    $('#tags-preview').empty()
    $.each $('#template_tag_list').val().split(','), (i, v) ->
      return if v == ''
      $('#tags-preview').append($('<li/>').append($('<span/>').text(v)))

  # 全プレビュー反映
  update_preview = ->
    update_title_preview()
    update_text_preview()
    update_tags_preview()

  # 画像マークダウンの挿入
  insertImgMd = (url) ->
    target = $('#template_text')
    img_md = "![#{url}](#{url})\n"
    insertAtCaret(target, img_md)
    update_text_preview()

  # ターゲット要素のカーソル位置にテキストを挿入
  insertAtCaret = (target, str) ->
    target.focus()
    if navigator.userAgent.match(/MSIE/)
      r = document.selection.createRange()
      r.text = str
      r.select()
    else
      s = target.val()
      p = target.get(0).selectionStart
      np = p + str.length
      target.val(s.substr(0, p) + str + s.substr(p))
      target.get(0).setSelectionRange(np, np)

  $ ->
    # ページ読み込み時にプレビュー反映
    update_preview()

    # 変更イベント
    $("#template_title").keyup update_title_preview
    $("#template_text").keyup update_text_preview
    $("#template_tag_list").keyup update_tags_preview

    $('#upload-btn').click ->
      $('#async-image-data')[0].click()
      return false


    # 画像アップロードボタン
    $('#async-image-data').change ->
      if $(@).files < 1
        return
      file = $(this)[0].files[0]
      if file.clientHeight > 2000 or file.clientWidth > 2000
        alert '画像アップロードでエラーが発生しました 画像サイズが大きいです'
        return

      fd = new FormData()
      fd.append('name', 'jquery test')
      fd.append('file', file)

      $.ajax
        url: '/api/v1/images/upload'
        method: "POST"
        data: fd
        processData: false
        contentType: false
        success: (json) ->
          url = json.file.url
          insertImgMd('http://' + window.location.host + url)
        error: (json) ->
          alert '画像アップロードでエラーが発生しました'
      $('#async-image-data').val('')

app/views/templates/_icons.html.slim
= link_to edit_template_path(@template) do
  = fa_icon 'pencil'

app/views/templates/_template.html.slim
li.article-item-box
  .article-icon
    = image_tag template.user.image.url, class: 'img-circle', size: '64x64'
  .info
    .info-head
      .created
        = render partial: 'articles/author_info', locals: {article: template}
    .info-title
      h2.title
        = link_to template.name, template
      = link_tags_list_for(template.tags)

app/views/templates/edit.html.slim
- provide(:title, @template.title)
.container-fluid
  h1.page-title
    | テンプレート編集
  .row
    .col-lg-6
      = render 'form'
    .col-lg-6
      ul#tags-preview.tag_list
      h2#title-preview
      hr
      #text-preview-area.markdown-body

app/views/templates/index.html.slim
.container
  h1.page-title
    |  テンプレート一覧
    - if params[:tag]
      = fa_icon 'tag'
      = params[:tag]
  ul.articles
    = render @templates
  = paginate @templates

app/views/templates/new.html.slim
- provide(:title, @template.title)
.container-fluid
  h1.page-title
    | テンプレート作成
  .row
    .col-lg-6
      = render 'form'
    .col-lg-6
      ul#tags-preview.tag_list
      h2#title-preview
      hr
      #text-preview-area.markdown-body

app/views/templates/show.html.slim
- provide(:title, @template.title)
.article-header
  .container
    .article-titles
      h1.title.emojable
        = @template.title
        = render partial: 'icons', locals: { article: @template }
      p.emojable = "【#{@template.name}】"
      = render partial: 'articles/author_info', locals: { article: @template }
      = render partial: 'articles/tag_list', locals: { article: @template }
      = link_to '削除', @template, method: :delete, data: { confirm: '本当に削除しますか？' }

.tag-header
  .container
    = render partial: 'articles/tag_list', locals: { article: @template }

.container
  .article-body.row
    .col-md-8
      .article-text
        #text-preview.markdown-body
          == markdown(@template.text)
    .col-md-4
      = image_tag @user.image.url, class: 'img-circle', size: '64x64'
      = link_to @user.screen_name, @user
      .article__show
        h4 新着の投稿
        = render partial: 'articles/article', collection: @recently_articles