config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'articles#index'

  mount API::Root => '/'
  mount GrapeSwaggerRails::Engine => '/docs'

  devise_for :users, :controllers => { :omniauth_callbacks => 'users/omniauth_callbacks' }

  devise_scope :user do
    get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  resources :articles do
    collection do
      match 'search' => 'articles#search', via: [:get, :post], as: :search
    end

    get 'history'
    get 'lock'
    get 'unlock'
  end

  resources :templates do
    get 'lock'
    get 'unlock'
  end

  resources :stars, only: [:create, :destroy]
  resources :comments, only: [:create, :update, :destroy]
  resources :uploader, only: [:index, :form, :upload, :download]
  resources :users, only: [:index]
  resources :users, path: '/', only: [:edit, :show, :update]
end

app/models/star.rb
# == Schema Information
#
# Table name: stars
#
#  id         :integer          not null, primary key
#  article_id :integer          not null
#  user_id    :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_stars_on_article_id  (article_id)
#  index_stars_on_user_id     (user_id)
#

class Star < ActiveRecord::Base
  belongs_to :article
  belongs_to :user

  validates :user, presence: true
  validates :article, presence: true
end

app/controllers/stars_controller.rb
class StarsController < ApplicationController
  before_action :set_star, only: [:destroy]

  # POST /stars
  # POST /stars.json
  def create
    @article = Article.find(star_params[:article_id])
    @star    = Star.new(star_params)
    @stars   = @article.stars.includes(:user)

    respond_to do |format|
      if @star.save
        format.js { render 'stars/stars' }
      else
        format.json { render json: @star.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stars/1
  # DELETE /stars/1.json
  def destroy
    article = @star.article
    @star.destroy
    @stars = article.stars.includes(:user)
    respond_to do |format|
      format.js { render 'stars/stars' }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_star
    @star = Star.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def star_params
    params.require(:star).permit(:user_id, :article_id)
  end
end

app/views/stars/_article_star.html.slim
= link_to star.user do
  = image_tag(star.user.image.thumb, size: '25x25')
  span.star__box
    = fa_icon 'star', class: 'star__box__star'

app/views/stars/_form.html.slim
= form_for(@star) do |f|
  - if @star.errors.any?
    #error_explanation
      h2
        = pluralize(@star.errors.count, "error")
        |  prohibited this star from being saved:
      ul
        - @star.errors.full_messages.each do |message|
          li
            = message
  .actions
    = f.submit

app/views/stars/_star.html.slim
- if current_user == star.user
  = link_to star_path(star), method: :delete, remote: true do
    = image_tag(star.user.image.thumb, size: '25x25')
    span.star__box
      = fa_icon 'star', class: 'star__box__star'
- else
  = link_to star.user do
    = image_tag(star.user.image.thumb, size: '25x25')
    span.star__box
      = fa_icon 'star', class: 'star__box__star'

app/views/stars/create.js.erb
$('#star__list').html("<%= j( render @stars ) %>");