config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'articles#index'

  mount API::Root => '/'
  mount GrapeSwaggerRails::Engine => '/docs'

  devise_for :users, :controllers => { :omniauth_callbacks => 'users/omniauth_callbacks' }

  devise_scope :user do
    get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  resources :articles do
    collection do
      match 'search' => 'articles#search', via: [:get, :post], as: :search
    end

    get 'history'
    get 'lock'
    get 'unlock'
  end

  resources :templates do
    get 'lock'
    get 'unlock'
  end

  resources :stars, only: [:create, :destroy]
  resources :comments, only: [:create, :update, :destroy]
  resources :uploader, only: [:index, :form, :upload, :download]
  resources :users, only: [:index]
  resources :users, path: '/', only: [:edit, :show, :update]
end

app/views/shared/_navbar.html.slim
#navbar.navbar.navbar-default
  .container
    .navbar-header
      = link_to '丼', root_path, class: 'navbar-brand'
      - if user_signed_in?
        = search_form_for @q, url: search_articles_path, class: 'form-group', html: { class: 'navbar-form navbar-left' } do |f|
          = f.search_field :title_or_user_screen_name_or_tags_name_cont, placeholder: '検索', class: 'form-control'
          = f.submit '検索', class: 'btn btn-default'
      ul.visible-xs.menus
        = menu_link_item('', :pencil, new_article_path, params[:controller] == 'articles' && (params[:action] == 'new' || params[:action] == 'edit'))
        = menu_link_item('', 'th-list', articles_path, params[:controller] == 'articles' && (params[:action] != 'new' && params[:action] != 'edit'))
        = menu_link_item('', :users, users_path, params[:controller] == 'users')
      button.navbar-toggle.collapsed[type="button" data-toggle="collapse" data-target="#navbar-user" aria-expanded="false"]
        = fa_icon 'user'
    #navbar-user.collapse.navbar-collapse
      ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          li.hidden-xs
            ul.menu_item
              // TODO: button
              = menu_link_item('作成', :pencil, new_article_path, params[:controller] == 'articles' && (params[:action] == 'new' || params[:action] == 'edit'))
              = menu_link_item('記事一覧', 'th-list', articles_path, params[:controller] == 'articles' && (params[:action] != 'new' && params[:action] != 'edit'))
              = menu_link_item('メンバー', :users, users_path, params[:controller] == 'users')
          li.hidden-xs
            = image_tag current_user.image.url, class: 'img-circle', size: '36x36'
          li.dropdown.hidden-xs
            = link_to '#', class: 'dropdown-toggle', data: { toggle: 'dropdown' } do
              = current_user.screen_name
              span.caret
            ul.dropdown-menu
              = menu_link_item('マイページ', :pencil, current_user, params[:controller] == 'users' && params[:action] == 'show')
              = menu_link_item('設定', :cog, edit_user_path(current_user), params[:controller] == 'users' && params[:action] == 'edit')
              = menu_link_item('ログアウト', 'sign-out', '/sign_out', false)
          li.visible-xs
            = link_to 'マイページ', current_user
          li.visible-xs
            = link_to '設定', edit_user_path(current_user)
          li.visible-xs
            = link_to 'ログアウト', '/sign_out'
        - else
          li
            = link_to 'Google ログイン', user_omniauth_authorize_path(:google_oauth2)

app/views/shared/_notice.html.slim
- flash.each do |type, message|
  |  <div class="alert
  == alert_class_for(type)
  |  alert-dismissible fade in">
  button.close[type="button" data-dismiss="alert"]
    span[aria-hidden="true"]
      | ×
    span.sr-only
      | Close
  == message